<?php

namespace Database\Seeders;

use App\Models\Painting;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaintingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paintings = [
            [
                'pid' => '29010',
                'genre_id' => 1,
                'artistID' => 29,
                'artistName' => 'Klimt',
                'paintingTitle' => 'The Kiss',
                'paintingDescription' => '<em>The Kiss</em> (original <em>Der Kuss</em>) was painted by Gustav Klimt, and is probably his most famous work. He began work on it in 1907 and it is the highpoint of his so-called Golden Period, when he painted a number of works in a similar style.',
                'paintingImage' => 'resources/images/paintingImages/29010.jpg',
                'paintingPrice' => 320.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1907,
            ],
            [
                'pid' => '29040',
                'genre_id' => 1,
                'artistID' => 29,
                'artistName' => 'Klimt',
                'paintingTitle' => 'Portrait of Adele Bloch-Bauer I',
                'paintingDescription' => 'This painting, which took three years to complete, was commissioned by the wealthy industrialist Ferdinand Bloch-Bauer, who made his money in the sugar industry. Ferdinand Bloch-Bauer favored the arts, especially Klimt, and commissioned him to complete another portrait of his wife Adele in 1912.',
                'paintingImage' => 'resources/images/paintingImages/29040.jpg',
                'paintingPrice' => 5000.00,
                'shippingCharge' => 0.00,
                'paintingYear' => 1907,
            ],
            // Add other paintings as needed...
            [
                'pid' => '01220',
                'genre_id' => 2,
                'artistID' => 1,
                'artistName' => 'Picasso',
                'paintingTitle' => 'Portrait of Dora Maar',
                'paintingDescription' => 'The canvas was one of many portraits of Dora Maar painted by Pablo Picasso over their nearly decade-long relationship. Picasso fell in love with the 29-year old Maar at the age of 55 and soon began living with her.',
                'paintingImage' => 'resources/images/paintingImages/01220.jpg',
                'paintingPrice' => 500.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1937,
            ], [
                'pid' => '01260',
                'genre_id' => 2,
                'artistID' => 1,
                'artistName' => 'Picasso',
                'paintingTitle' => 'Three Musicians',
                'paintingDescription' => '<em>Three Musicians</em> is the title of two similar collage and oil paintings by Spanish artist Pablo Picasso. They were both completed in 1921 in Fontainebleau near Paris, France, and exemplify the Synthetic Cubist style. Each painting features a Harlequin, a Pierrot, and a monk, who are generally believed to represent Picasso, Guillaume Apollinaire, and Max Jacob, respectively.',
                'paintingImage' => 'resources/images/paintingImages/01260.jpg',
                'paintingPrice' => 500.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1921,
            ],

            [
                'pid' => '02010',
                'genre_id' => 3,
                'artistID' => 2,
                'artistName' => 'Matisse',
                'paintingTitle' => 'Woman With Hat',
                'paintingDescription' => '<em>Woman with a Hat</em> (La femme au chapeau) is a painting by Henri Matisse from 1905. It is believed that the woman in the painting was Matisse\'s wife, Amelie.',
                'paintingImage' => 'resources/images/paintingImages/02010.jpg',
                'paintingPrice' => 340.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1905,
            ],
            [
                'pid' => '2030',
                'genre_id' => 3,
                'artistID' => 2,
                'artistName' => 'Matisse',
                'paintingTitle' => 'Joy of Life',
                'paintingDescription' => '<em>Le bonheur de vivre</em> (The Joy of Life), is a painting by Henri Matisse. In the central background of the piece is a group of figures that is similar to the group depicted in his painting The Dance (second version).',
                'paintingImage' => 'resources/images/paintingImages/02030.jpg',
                'paintingPrice' => 340.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1905,
            ],
            [
                'pid' => '02070',
                'genre_id' => 3,
                'artistID' => 2,
                'artistName' => 'Matisse',
                'paintingTitle' => 'The Red Madras Headdress',
                'paintingDescription' => '<em>The Red Madras Headdress</em> is a painting by Henri Matisse from 1907. The woman depicted is the painter\'s wife, Amélie Noellie Parayre Matisse.',
                'paintingImage' => 'resources/images/paintingImages/02070.jpg',
                'paintingPrice' => 400.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1907,
            ],
            [
                'pid' => '14010',
                'genre_id' => 4,
                'artistID' => 14,
                'artistName' => 'Renoir',
                'paintingTitle' => 'Dance at Le Moulin de la Galette',
                'paintingDescription' => '<em>Dance at Moulin de la Galette</em> is one of Impressionism’s most highly revered masterpieces. The scene is of a Sunday afternoon at Moulin de la Galette, where Parisians would typically dress up and spend all day dancing, drinking, and eating galettes, or flat cakes.',
                'paintingImage' => 'resources/images/paintingImages/14010.jpg',
                'paintingPrice' => 4550.00,
                'shippingCharge' => 0.00,
                'paintingYear' => 1876,
            ],
            [
                'pid' => '14020',
                'genre_id' => 4,
                'artistID' => 14,
                'artistName' => 'Renoir',
                'paintingTitle' => 'Luncheon Boating Party',
                'paintingDescription' => 'The painting depicts a group of Renoir\'s friends relaxing on a balcony at the Maison Fournaise along the Seine river in Chatou, France. The painter and art patron, Gustave Caillebotte, is seated in the lower right. Renoir\'s future wife, Aline Charigot, is in the foreground playing with a small dog.',
                'paintingImage' => 'resources/images/paintingImages/14020.jpg',
                'paintingPrice' => 380.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1881,
            ],
            [
                'pid' => '17010',
                'genre_id' => 4,
                'artistID' => 17,
                'artistName' => 'Monet',
                'paintingTitle' => 'Impression Sunrise',
                'paintingDescription' => 'In 1872, Monet painted <em>Impression, Sunrise</em> (Impression, soleil levant) depicting a Le Havre port landscape. It hung in the first Impressionist exhibition in 1874.',
                'paintingImage' => 'resources/images/paintingImages/17010.jpg',
                'paintingPrice' => 130.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1872,
            ],
            [
                'pid' => '17020',
                'genre_id' => 4,
                'artistID' => 17,
                'artistName' => 'Monet',
                'paintingTitle' => 'Women in the Garden',
                'paintingDescription' => 'Monet’s technique of “en plein air” painting was hard at work on this painting. Because it necessitated that he work from the same point of view as he painted, he dug a trench for the bottom half of the painting to sit in while he painted the top, due to its large size.',
                'paintingImage' => 'resources/images/paintingImages/17020.jpg',
                'paintingPrice' => 1050.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1866,
            ],
            [
                'pid' => '13010',
                'genre_id' => 4,
                'artistID' => 13,
                'artistName' => 'Whistler',
                'paintingTitle' => 'Symphony in White, No. 1: The White Girl',
                'paintingDescription' => '<em>Symphony in White, No. 1</em>, also known as <em>The White Girl</em>, is a painting by James Abbott McNeill Whistler. The work shows a woman in full figure standing on a wolf skin in front of a white curtain with a lily in her hand.',
                'paintingImage' => 'resources/images/paintingImages/13010.jpg',
                'paintingPrice' => 300.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1862,
            ],
            [
                'pid' => '13030',
                'genre_id' => 4,
                'artistID' => 13,
                'artistName' => 'Whistler',
                'paintingTitle' => 'Arrangement in Grey and Black: Portrait of the Painter\'s Mother',
                'paintingDescription' => '<em>Arrangement in Grey and Black: The Artist\'s Mother</em>, famous under its colloquial name Whistler\'s Mother, is an 1871 oil-on-canvas painting by American-born painter James McNeill Whistler. It occasionally tours worldwide. Although an icon of American art, it rarely appears in the United States.',
                'paintingImage' => 'resources/images/paintingImages/13030.jpg',
                'paintingPrice' => 300.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1871,
            ],
            [
                'pid' => '01070',
                'genre_id' => 5,
                'artistID' => 1,
                'artistName' => 'Picasso',
                'paintingTitle' => 'The Actor',
                'paintingDescription' => 'Picasso painted <em>The Actor</em> over another painting, because he could not afford new canvases at the time. He created the painting over the winter of 1904–1905, at the age of 23. This was during the artist\'s Rose Period, when he changed his painting style from the downbeat tones of his Blue Period to warmer and more romantic hues.',
                'paintingImage' => 'resources/images/paintingImages/01070.jpg',
                'paintingPrice' => 200.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1904,
            ],
            [
                'pid' => '01080',
                'genre_id' => 5,
                'artistID' => 1,
                'artistName' => 'Picasso',
                'paintingTitle' => 'Family of Saltimbanques',
                'paintingDescription' => '<em>Family of Saltimbanques</em> (La famille de saltimbanques) is a 1905 painting by Pablo Picasso. It is considered the masterpiece of Picasso\'s circus period.',
                'paintingImage' => 'resources/images/paintingImages/01080.jpg',
                'paintingPrice' => 160.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1905,
            ],
            [
                'pid' => '19030',
                'genre_id' => 5,
                'artistID' => 19,
                'artistName' => 'Van Gogh',
                'paintingTitle' => 'Sidewalk Café at Night',
                'paintingDescription' => '<em>Café Terrace at Night</em>, also known as The Cafe Terrace on the Place du Forum, is an oil painting on an industrially primed canvas of size 25 in Arles, France, mid-September 1888.',
                'paintingImage' => 'resources/images/paintingImages/19030.jpg',
                'paintingPrice' => 300.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1888,
            ],
            [
                'pid' => '19040',
                'genre_id' => 5,
                'artistID' => 19,
                'artistName' => 'Van Gogh',
                'paintingTitle' => 'Décoration for the Yellow House',
                'paintingDescription' => '<em>Sunflowers</em> (original title, in French: Tournesols) are the subject of two series of still life paintings by Vincent van Gogh. The first series, executed in Paris in 1887, depicts the flowers lying on the ground, while the second, made a year later in Arles, shows a bouquet of sunflowers in a vase.',
                'paintingImage' => 'resources/images/paintingImages/19040.jpg',
                'paintingPrice' => 300.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1888,
            ],
            [
                'pid' => '19050',
                'genre_id' => 5,
                'artistID' => 19,
                'artistName' => 'Van Gogh',
                'paintingTitle' => 'Sunflowers',
                'paintingDescription' => '<em>Sunflowers</em> (original title, in French: Tournesols) are the subject of two series of still life paintings by the Dutch painter Vincent van Gogh. The earlier series executed in Paris in 1887 gives the flowers lying on the ground, while the second set executed a year later in Arles shows bouquets of sunflowers in a vase.',
                'paintingImage' => 'resources/images/paintingImages/19050.jpg',
                'paintingPrice' => 400.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1888,
            ],
            [
                'pid' => '19070',
                'genre_id' => 5,
                'artistID' => 19,
                'artistName' => 'Van Gogh',
                'paintingTitle' => 'Starry Night',
                'paintingDescription' => 'In the later part of his life, Van Gogh committed himself to an asylum in Saint Remy de Provence. <em>The Starry Night</em> was the view from the window in Van Gogh’s sanitarium bedroom. Although it is a night scene, it was painted during the day.',
                'paintingImage' => 'resources/images/paintingImages/19070.jpg',
                'paintingPrice' => 410.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1889,
            ],
            [
                'pid' => '19100',
                'genre_id' => 5,
                'artistID' => 19,
                'artistName' => 'Van Gogh',
                'paintingTitle' => 'The Night Café',
                'paintingDescription' => '<em>The Night Café</em> (original French title: <em>Le Café de nuit</em>) is an oil painting created in Arles in September 1888, by Vincent van Gogh. Its title is inscribed lower right beneath the signature.',
                'paintingImage' => 'resources/images/paintingImages/19100.jpg',
                'paintingPrice' => 360.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1888,
            ],
            [
                'pid' => '05010',
                'genre_id' => 6,
                'artistID' => 5,
                'artistName' => 'David',
                'paintingTitle' => 'The Oath of the Horatii',
                'paintingDescription' => '<em>Oath of the Horatii</em> (French: Le Serment des Horaces), is a work by French artist Jacques-Louis David painted in 1784. It depicts a scene from a Roman legend about a dispute between two warring cities; Rome and Alba Longa, when three brothers from a Roman family, the Horatii, agree to end the war by fighting three brothers from an Alba Longa family, the Curiatii.',
                'paintingImage' => 'resources/images/paintingImages/05010.jpg',
                'paintingPrice' => 800.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1784,
            ],
            [
                'pid' => '05030',
                'genre_id' => 6,
                'artistID' => 5,
                'artistName' => 'David',
                'paintingTitle' => 'The Death of Marat',
                'paintingDescription' => '<em>The Death of Marat</em> (French: <em>La Mort de Marat</em>) is a 1793 painting in the Neoclassical style by Jacques-Louis David, and is one of the most famous images of the French Revolution.',
                'paintingImage' => 'resources/images/paintingImages/05030.jpg',
                'paintingPrice' => 450.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1793,
            ],
            [
                'pid' => '05050',
                'genre_id' => 6,
                'artistID' => 5,
                'artistName' => 'David',
                'paintingTitle' => 'Napoleon Crossing the Alps',
                'paintingDescription' => '<em>Napoleon Crossing the Alps</em> (also known as <em>Napoleon at the Saint-Bernard Pass</em> or <em>Bonaparte Crossing the Alps</em>) is the title given to the five versions of an oil on canvas equestrian portrait of Napoleon Bonaparte painted by the French artist Jacques-Louis David between 1801 and 1805.',
                'paintingImage' => 'resources/images/paintingImages/05050.jpg',
                'paintingPrice' => 250.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1800,
            ],
            [
                'pid' => '06010',
                'genre_id' => 6,
                'artistID' => 6,
                'artistName' => 'Ingres',
                'paintingTitle' => 'Mademoiselle Caroline Riviere',
                'paintingDescription' => 'The portrait of Mademoiselle Caroline Rivière was painted in 1806 by the French Neoclassical artist Jean Auguste Dominique Ingres, and today hangs in the Louvre. It is the third of three portraits of the Rivière family the artist painted that year.',
                'paintingImage' => 'resources/images/paintingImages/06010.jpg',
                'paintingPrice' => 400.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1806,
            ],
            [
                'pid' => '06020',
                'genre_id' => 6,
                'artistID' => 6,
                'artistName' => 'Ingres',
                'paintingTitle' => 'Betty de Rothschild, Baronne de Rothschild',
                'paintingDescription' => '<em>Baronne de Rothschild</em> is a 1848 oil and canvas portrait by the French Neoclassical artist Jean Auguste Dominique Ingres. The sitter, Betty de Rothschild (1805-1886) had married banker James Mayer de Rothschild and was one of the wealthiest women in northern Europe, and one of the foremost Parisian patrons of the arts.',
                'paintingImage' => 'resources/images/paintingImages/06020.jpg',
                'paintingPrice' => 550.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1848,
            ],
            [
                'pid' => '06030',
                'genre_id' => 6,
                'artistID' => 6,
                'artistName' => 'Ingres',
                'paintingTitle' => 'La Grande Odalisque',
                'paintingDescription' => '<em>Grande Odalisque</em>, also known as Une Odalisque or La Grande Odalisque, is an oil painting of 1814 by Jean Auguste Dominique Ingres depicting an odalisque, or concubine. Ingres contemporaries considered the work to signify Ingres break from Neoclassicism, indicating a shift toward exotic Romanticism.',
                'paintingImage' => 'resources/images/paintingImages/06030.jpg',
                'paintingPrice' => 175.00,
                'shippingCharge' => 20.00,
                'paintingYear' => 1814,
            ],


        ];

        foreach ($paintings as $painting) {
            Painting::create($painting);
        }

    }
}
